// src/components/ui/footer.tsx
"use client";

import Link from "next/link";
import { Facebook, Twitter, Instagram, Linkedin, Mail, Phone, MapPin, Globe } from "lucide-react";
import { useLanguage } from "@/context/language-context";
import { LanguageSwitcher } from "@/components/language-switcher";
import { LogoSvg } from "./logo-svg";
import { usePathname } from "next/navigation";

export function Footer() {
  const currentYear = new Date().getFullYear();
  const { t } = useLanguage();
  const pathname = usePathname();

  // Función para manejar el scroll suave hacia los anclajes
  const handleAnchorClick = (e: React.MouseEvent<HTMLAnchorElement>, anchorId: string) => {
    e.preventDefault();

    // Solo scroll si estamos en la página principal
    if (pathname === '/') {
      const element = document.getElementById(anchorId);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    } else {
      // Si estamos en otra página, navegar a la página principal con hash
      window.location.href = `/#${anchorId}`;
    }
  };

  return (
    <footer className="bg-primary text-white">
      <div className="container-custom py-16">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Column 1 - Logo & Description */}
          <div className="space-y-4">
            <div className="flex items-center justify-center lg:justify-start">
              <LogoSvg width={50} height={50} variant="light" className="scale-125" />
            </div>
            <p className="text-white/80 max-w-xs">
              {t("footer.tagline")}
            </p>
          </div>

          {/* Column 2 - Quick Links */}
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-white">Quick Links</h4>
            <ul className="space-y-2">
              <li>
                <Link
                  href="/#home"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'home')}
                >
                  Home
                </Link>
              </li>
              <li>
                <Link
                  href="/#servicios"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'servicios')}
                >
                  Services
                </Link>
              </li>
              <li>
                <Link
                  href="/#proyectos"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'proyectos')}
                >
                  Projects
                </Link>
              </li>
              <li>
                <Link
                  href="/#sobre-nosotros"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'sobre-nosotros')}
                >
                  About Us
                </Link>
              </li>
              <li>
                <Link href="/blog" className="text-white/70 hover:text-white transition-colors">
                  Blog
                </Link>
              </li>
            </ul>
          </div>

          {/* Column 3 - Services */}
          <div className="space-y-4">
            <h4 className="text-lg font-semibold text-white">Services</h4>
            <ul className="space-y-2">
              <li>
                <Link
                  href="/#servicios"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'servicios')}
                >
                  Digital Marketing
                </Link>
              </li>
              <li>
                <Link
                  href="/#servicios"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'servicios')}
                >
                  Web Development
                </Link>
              </li>
              <li>
                <Link
                  href="/#servicios"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'servicios')}
                >
                  UX/UI Design
                </Link>
              </li>
              <li>
                <Link
                  href="/#servicios"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'servicios')}
                >
                  Software Development
                </Link>
              </li>
              <li>
                <Link
                  href="/#servicios"
                  className="text-white/70 hover:text-white transition-colors"
                  onClick={(e) => handleAnchorClick(e, 'servicios')}
                >
                  Digital Strategy
                </Link>
              </li>
            </ul>
          </div>

          {/* Column 4 - Contact Information */}
          <div className="space-y-4 lg:col-span-3 flex flex-col lg:flex-row lg:justify-between items-center border-t border-white/20 pt-8 mt-8">
            {/* Social Media Icons */}
            <div className="flex space-x-6 mb-6 lg:mb-0">
              <Link href="#" className="text-white/70 hover:text-white transition-colors" aria-label="Facebook">
                <Facebook size={20} />
              </Link>
              <Link href="#" className="text-white/70 hover:text-white transition-colors" aria-label="Twitter">
                <Twitter size={20} />
              </Link>
              <Link href="#" className="text-white/70 hover:text-white transition-colors" aria-label="Instagram">
                <Instagram size={20} />
              </Link>
              <Link href="#" className="text-white/70 hover:text-white transition-colors" aria-label="LinkedIn">
                <Linkedin size={20} />
              </Link>
            </div>

            {/* Contact Info */}
            <div className="flex flex-col lg:flex-row items-center gap-6">
              <div className="flex items-center gap-3">
                <Phone className="text-secondary flex-shrink-0" size={18} />
                <span className="text-white/70">+1 (786) 480-3088</span>
              </div>
              <div className="flex items-center gap-3">
                <Mail className="text-secondary flex-shrink-0" size={18} />
                <span className="text-white/70">info@swiftzone.com</span>
              </div>
              <div>
                <LanguageSwitcher
                  variant="full"
                  className="text-white bg-primary-foreground/10 hover:bg-white/20"
                />
              </div>
            </div>
          </div>
        </div>

        <div className="border-t border-white/20 mt-12 pt-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-sm text-white/70">
              © {currentYear} SwiftZone. All rights reserved.
            </p>
            <div className="flex space-x-6">
              <Link href="/privacy-policy" className="text-sm text-white/70 hover:text-white transition-colors">
                Privacy Policy
              </Link>
              <Link href="/terms-conditions" className="text-sm text-white/70 hover:text-white transition-colors">
                Terms & Conditions
              </Link>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// components/ui/Footer.vue
<template>
  <footer class="bg-primary text-white pt-16 pb-8">
    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
        <!-- Company Info -->
        <div>
          <img src="public/logo-white.svg" alt="SwiftZone" class="h-10 mb-6" />
          <p class="text-white mb-6">
            {{ t("footer.tagline") }}
          </p>
        </div>

        <!-- Quick Links -->
        <div>
          <h3 class="text-lg font-semibold mb-6">
            {{ t("footer.quickLinks") }}
          </h3>
          <ul class="space-y-3">
            <li>
              <router-link to="/" class="text-white hover:text-white">
                {{ t("nav.home") }}
              </router-link>
            </li>
            <li>
              <router-link to="/#services" class="text-white hover:text-white">
                {{ t("nav.services") }}
              </router-link>
            </li>
            <li>
              <router-link to="/#projects" class="text-white hover:text-white">
                {{ t("nav.projects") }}
              </router-link>
            </li>
            <li>
              <router-link to="/#aboutus" class="text-white hover:text-white">
                {{ t("nav.about") }}
              </router-link>
            </li>
            <li>
              <router-link to="/blog" class="text-white hover:text-white">
                {{ t("nav.blog") }}
              </router-link>
            </li>
          </ul>
        </div>

        <!-- Services -->
        <div>
          <h3 class="text-lg font-semibold mb-6">{{ t("footer.services") }}</h3>
          <ul class="space-y-3">
            <li>
              <router-link
                to="/services/web-development"
                class="text-white hover:text-white"
              >
                {{ t("services.web") }}
              </router-link>
            </li>
            <li>
              <router-link
                to="/services/software-development"
                class="text-white hover:text-white"
              >
                {{ t("services.software") }}
              </router-link>
            </li>
            <li>
              <router-link
                to="/services/digital-marketing"
                class="text-white hover:text-white"
              >
                {{ t("services.marketing") }}
              </router-link>
            </li>
            <li>
              <router-link
                to="/services/ux-ui-design"
                class="text-white hover:text-white"
              >
                {{ t("services.uxui") }}
              </router-link>
            </li>
            <li>
              <router-link
                to="/services/digital-strategy"
                class="text-white hover:text-white"
              >
                {{ t("services.strategy") }}
              </router-link>
            </li>
          </ul>
        </div>

        <!-- Contact Info -->
        <div>
          <h3 class="text-lg font-semibold mb-6">{{ t("footer.contact") }}</h3>
          <ul class="space-y-3">
            <li class="flex items-start">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6 mr-2 text-white"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                />
              </svg>
              <span class="text-white"> +1 (786) 480-3088 </span>
            </li>
            <li class="flex items-start">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6 mr-2 text-white"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                />
              </svg>
              <span class="text-white"> info@swiftzone.com </span>
            </li>

            <li class="flex items-start">
              <div class="flex space-x-4">
                <a href="https://x.com/swiftzonedev" class="text-white hover:text-white">
                  <Icon name="bi:twitter-x" />
                </a>
                <a href="https://www.instagram.com/swiftzone.dev/" class="text-white hover:text-white">
                  <Icon name="bi:instagram" />
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <!-- Copyright -->
      <div class="border-t border-gray-800 mt-12 pt-8">
        <div class="flex flex-col md:flex-row justify-between items-center">
          <p class="text-white text-sm">
            &copy; {{ new Date().getFullYear() }} SwiftZone.
            {{ t("footer.rights") }}
          </p>
          <div class="flex space-x-6 mt-4 md:mt-0">
            <router-link
              to="/privacy-policy"
              class="text-white hover:text-white text-sm"
            >
              {{ t("footer.privacy") }}
            </router-link>
            <router-link
              to="/terms-conditions"
              class="text-white hover:text-white text-sm"
            >
              {{ t("footer.terms") }}
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup>
import { useLanguage } from "~/context/language-context";

const { t } = useLanguage();
</script>
